config/routes.rb
Rails.application.routes.draw do

  resources :contact

  get 'reportes/reportes'
  get 'reportes/clientes'
  get 'reportes/usuarios'
  get 'reportes/empleados'

  get 'registration_clients/mis_paquetes'

  get 'checkouts/index'
  post :save_checkout, to: 'checkouts#save_checkout'
  get :view_checkout, to: 'checkouts#view_checkout'
  post :confirm_checkout, to: 'checkouts#confirm_checkout'

  devise_for :clients, controllers: { sessions: 'clients/sessions', 
                                      registrations: 'clients/registrations',
                                      confirmations: 'clients/confirmations',
                                      passwords: 'clients/passwords' }

  devise_for :users, controllers: { sessions: 'users/sessions', 
                                    registrations: 'users/registrations',
                                    confirmations: 'users/confirmations',
                                    passwords: 'users/passwords' }

  root to: 'static_pages#home'
  get :admin_home, to: 'admin#home'

  #Paginas estaticas
  get :quienes_somos, to: 'static_pages#who_we_are'
  get :servicios, to: 'static_pages#services'
  get :contacto, to: 'static_pages#contact'

  resources :registrations
  resources :employees
  resources :registration_clients
  resources :packs
  resources :vehiculos
  resources :rutas

  get :select_vehiculo, to: 'rutas#select_vehiculo'
  post :confirm_vehiculo, to: 'rutas#confirm_vehiculo'

  get :select_packs, to: 'rutas#select_packs'
  post :confirm_packs, to: 'rutas#confirm_packs'

  get :select_ruta, to: 'rutas#select_ruta'
  post :confirmar_rutas, to: 'rutas#confirmar_rutas'

  get :index_rutas, to: 'rutas#index_rutas'

  post :client_modal_create, to: 'registration_clients#modal_create'
  get '/json_client/(:id)', to: 'registration_clients#json_client'

  get :nomina, to: 'employees#nomina'
end

app/models/employee.rb
# Model Employee
class Employee < ApplicationRecord
  validates :name, :last_name, :birth, :pay_rate, :residence, :email, presence: true
  validates :email, presence: :true, uniqueness: :true

  scope :without_user, -> { joins('LEFT JOIN users s ON employees.id = s.employee_id WHERE s.employee_id IS NULL ') }
  scope :concat_last_name, -> { pluck("initcap(employees.last_name) || ' ' || initcap(employees.name), employees.id") }
end

app/controllers/employees_controller.rb
# Controller Employee
class EmployeesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_model

  def index
    @employees = Employee.all.order(:last_name)
  end

  def nomina
    @employees = Employee.all.order(:last_name)
  end

  def new
  end

  def edit
  end
  
  def create
    employee = Employee.new employee_params
    if employee.save
      flash[:notice] = 'Empleado creado'
      redirect_to employees_path
    else
      flash[:alert] = employee.errors
      redirect_to new_employee_path
    end
  end

  def update
    if @employee.update_attributes employee_params
      flash[:notice] = 'Empleado actualizado'
      redirect_to employees_path
    else
      flash[:alert] = @employee.errors
      redirect_to new_employee_path
    end
  end
  
  def destroy
    if @employee.destroy
      flash[:notice] = 'Empleado eliminado'
      redirect_to employees_path
    else
      flash[:alert] = @employee.errors
      redirect_to edit_employee_path
    end
  end
  
  private
  def find_model
    @employee = Employee.find(params[:id]) if params[:id]
  end

  def employee_params
    params.require(:employee).permit(:name, :last_name, :birth,
                                     :pay_rate, :email, :phone,
                                     :residence)
  end
end

app/views/employees/_form.html.erb
<%= form_for(form_model, url: form_url, method: form_method) do |f| %>
  <div class="row">
    <div class="col-md-6 form-group">
      <%= f.label :last_name %>
      <%= f.text_field :last_name, class: 'form-control'  %>
    </div>
    <div class="col-md-6 form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 form-group">
      <%= f.label :birth %>
      <%= f.date_field :birth, class: 'form-control'  %>
    </div>
    <div class="col-md-6 form-group">
      <%= f.label :pay_rate %>
      <%= f.number_field :pay_rate, class: 'form-control'  %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 form-group">
      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control'  %>
    </div>
    <div class="col-md-6 form-group">
        <%= f.label :phone %>
        <%= f.text_field :phone, class: 'form-control'  %>
    </div>
  </div>
  <div class="form-group">
      <%= f.label :residence %>
      <%= f.text_field :residence, class: 'form-control'  %>
  </div>
  <div>
      <%= f.submit :guardar, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<div id="EditEmployee" class="animated fadeIn">

  <h1 class="title">Editar Empleado</h1>

  <%= link_to employees_path do %>
    <%= fa_icon "chevron-left" %>
    <span>Regresar</span>
  <%- end %>

  <div class="col-md-8">
    <%= render 'form', form_model: @employee, form_url: employee_path(@employee.id), form_method: :patch %>
  </div>
</div>

app/views/employees/index.html.erb
<div class="animated fadeIn">
  
  <h1 class="title">Listado Empleados</h1>

  <%= link_to admin_home_path do %>
    <%= fa_icon "chevron-left" %>
    <span>Regresar</span>
  <%- end %>
  <%= link_to new_employee_path do %>
    <%= fa_icon "user-plus" %>
    <span>Nuevo Empleado</span>
  <%- end %>

  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Apellidos</th>
        <th scope="col">Nombres</th>
        <th scope="col">Fecha Nacimiento</th>
        <th scope="col">Tabulación</th>
        <th scope="col">Email</th>
        <th scope="col">Teléfono</th>
        <th scope="col">Residencia</th>
        <th scope="col">Empleado desde</th>
        <th scope="col">Opciones</th>
      </tr>
    </thead>
    <tbody>
      <% @employees.each do |employee| %>
        <tr>
          <th scope="row"><%= employee.last_name.titleize %></th>
          <td><%= employee.name.titleize %></td>
          <td><%= employee.birth %></td>
          <td><%= employee.pay_rate %></td>
          <td><%= employee.email %></td>
          <td><%= employee.phone %></td>
          <td><%= employee.residence[0..30] %></td>
          <td><%= employee.created_at.to_date %></td>
          <td>
              <%= link_to edit_employee_path(employee.id) do %>
                <%= fa_icon "edit 2x" %>
              <%- end %>
              <%= link_to employee_path(employee.id), method: :delete, data: { confirm: 'Está seguro que desea borrar este elemento?' } do %>
                <%= fa_icon "trash 2x" %>
              <%- end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/employees/new.html.erb
<div id="NewEmployee" class="animated fadeIn">

  <h1 class="title">Nuevo Empleado</h1>

  <%= link_to employees_path do %>
    <%= fa_icon "chevron-left" %>
    <span>Regresar</span>
  <%- end %>

  <div class="col-md-8">
  <%= render 'form', form_model: :employee, form_url: employees_url, form_method: :post %>
  </div>
</div>

app/views/employees/nomina.html.erb
<div class="animated fadeIn">
  
  <h1 class="title">Nómina</h1>

  <%= link_to admin_home_path do %>
    <%= fa_icon "chevron-left" %>
    <span>Regresar</span>
  <%- end %>

  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Apellidos</th>
        <th scope="col">Nombres</th>
        <th scope="col">Fecha Nacimiento</th>
        <th scope="col">Tabulación</th>
        <th scope="col">Días</th>
        <th scope="col">Pago</th>
      </tr>
    </thead>
    <tbody>
      <% @employees.each do |employee| %>
        <tr>
          <th scope="row"><%= employee.last_name.titleize %></th>
          <td><%= employee.name.titleize %></td>
          <td><%= employee.birth %></td>
          <td><%= employee.pay_rate %></td>
          <td><input type="number" id="nomina_row_<%= employee.id %>" data-tabulation="<%= employee.pay_rate %>" value="30"/></td>
          <td id="nomina_pay_<%= employee.id %>"><%= employee.pay_rate * 30 %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>