config/routes.rb
Rails.application.routes.draw do

  resources :contact

  get 'reportes/reportes'
  get 'reportes/clientes'
  get 'reportes/usuarios'
  get 'reportes/empleados'

  get 'registration_clients/mis_paquetes'

  get 'checkouts/index'
  post :save_checkout, to: 'checkouts#save_checkout'
  get :view_checkout, to: 'checkouts#view_checkout'
  post :confirm_checkout, to: 'checkouts#confirm_checkout'

  devise_for :clients, controllers: { sessions: 'clients/sessions', 
                                      registrations: 'clients/registrations',
                                      confirmations: 'clients/confirmations',
                                      passwords: 'clients/passwords' }

  devise_for :users, controllers: { sessions: 'users/sessions', 
                                    registrations: 'users/registrations',
                                    confirmations: 'users/confirmations',
                                    passwords: 'users/passwords' }

  root to: 'static_pages#home'
  get :admin_home, to: 'admin#home'

  #Paginas estaticas
  get :quienes_somos, to: 'static_pages#who_we_are'
  get :servicios, to: 'static_pages#services'
  get :contacto, to: 'static_pages#contact'

  resources :registrations
  resources :employees
  resources :registration_clients
  resources :packs
  resources :vehiculos
  resources :rutas

  get :select_vehiculo, to: 'rutas#select_vehiculo'
  post :confirm_vehiculo, to: 'rutas#confirm_vehiculo'

  get :select_packs, to: 'rutas#select_packs'
  post :confirm_packs, to: 'rutas#confirm_packs'

  get :select_ruta, to: 'rutas#select_ruta'
  post :confirmar_rutas, to: 'rutas#confirmar_rutas'

  get :index_rutas, to: 'rutas#index_rutas'

  post :client_modal_create, to: 'registration_clients#modal_create'
  get '/json_client/(:id)', to: 'registration_clients#json_client'

  get :nomina, to: 'employees#nomina'
end

app/models/vehiculo.rb
class Vehiculo < ApplicationRecord
end

app/controllers/vehiculos_controller.rb
#Controlador Vehiculos
class VehiculosController < ApplicationController
  before_action :authenticate_user!
  before_action :find_model

  def index
    @vehiculos = Vehiculo.all
  end

  def new
  end

  def edit
  end

  def create
    @vehiculo = Vehiculo.new vehiculo_params
    if @vehiculo.save
      flash[:notice] = 'Vehiculo creado'
      redirect_to vehiculos_path
    else
      flash[:alert] = @vehiculo.errors
      redirect_to new_vehiculo_path
    end
  end

  def update
    if @vehiculo.update_attributes vehiculo_params
      flash[:notice] = 'Vehiculo creado'
      redirect_to vehiculos_path
    else
      flash[:alert] = @vehiculo.errors
      redirect_to new_vehiculo_path
    end
  end

  def destroy
    if @vehiculo.destroy
      flash[:notice] = 'Vehiculo eliminado'
      redirect_to vehiculos_path
    else
      flash[:alert] = @vehiculo.errors
      redirect_to edit_vehiculo_path
    end
  end

  private
  def find_model
    @vehiculo = Vehiculo.find(params[:id]) if params[:id]
  end

  def vehiculo_params
    params.require(:vehiculo).permit(:marca,:modelo,:max_volumen,:max_peso)
  end
end

app/helpers/vehiculos_helper.rb
module VehiculosHelper
end

app/views/vehiculos/_form.html.erb
<%= form_for(form_model, url: form_url, method: form_method) do |f| %>
  <div class="row">
    <div class="col-md-6 form-group">
      <%= f.label :marca %>
      <%= f.text_field :marca, class: 'form-control'  %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 form-group">
      <%= f.label :modelo %>
      <%= f.text_field :modelo, class: 'form-control' %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 form-group">
      <%= f.label :max_volumen %>
      <%= f.number_field :max_volumen, class: 'form-control' %>
      <p style="color: green;">cm^3</p>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 form-group">
      <%= f.label :max_peso %>
      <%= f.number_field :max_peso, class: 'form-control' %>
      <p style="color: green;">kg</p>
    </div>
  </div>
  <div>
      <%= f.submit :guardar, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/vehiculos/create.html.erb
<h1>Vehiculos#create</h1>
<p>Find me in app/views/vehiculos/create.html.erb</p>

app/views/vehiculos/destroy.html.erb
<h1>Vehiculos#destroy</h1>
<p>Find me in app/views/vehiculos/destroy.html.erb</p>

app/views/vehiculos/edit.html.erb
<div id="EditVehiculo" class="animated fadeIn">

  <h1 class="title">Editar Vehiculo</h1>

  <%= link_to vehiculos_path do %>
    <%= fa_icon "chevron-left" %>
    <span>Regresar</span>
  <%- end %>

  <div class="col-md-8">
  <%= render 'form', form_model: :vehiculo, form_url: vehiculo_url(@vehiculo.id), form_method: :patch %>
  </div>
</div>

app/views/vehiculos/index.html.erb
<div class="animated fadeIn">
  
  <h1 class="title">Listado Vehiculos</h1>

  <%= link_to admin_home_path do %>
    <%= fa_icon "chevron-left" %>
    <span>Regresar</span>
  <%- end %>
  <%= link_to new_vehiculo_path do %>
    <%= fa_icon "user-plus" %>
    <span>Nuevo Vehiculo</span>
  <%- end %>

  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Marca</th>
        <th scope="col">Modelo</th>
        <th scope="col">Max Volumen (cm^3)</th>
        <th scope="col">Max Peso (Kg) </th>
        <th scope="col">Opciones</th>
      </tr>
    </thead>
    <tbody>
      <% @vehiculos.each do |vehiculo| %>
        <tr>
          <td scope="row"><%= vehiculo.marca.titleize %></td>
          <td scope="row"><%= vehiculo.modelo.titleize %></td>
          <td scope="row"><%= vehiculo.max_volumen %></td>
          <td scope="row"><%= vehiculo.max_peso %></td>
          <td>
            <%= link_to edit_vehiculo_path(vehiculo.id) do %>
              <%= fa_icon "edit 2x" %>
            <%- end %>
            <%= link_to vehiculo_path(vehiculo.id), method: :delete, data: { confirm: 'Está seguro que desea borrar este elemento?' } do %>
              <%= fa_icon "trash 2x" %>
            <%- end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/vehiculos/new.html.erb
<div id="NewVehiculo" class="animated fadeIn">

  <h1 class="title">Nuevo Vehiculo</h1>

  <%= link_to vehiculos_path do %>
    <%= fa_icon "chevron-left" %>
    <span>Regresar</span>
  <%- end %>

  <div class="col-md-8">
  <%= render 'form', form_model: :vehiculo, form_url: vehiculos_url, form_method: :post %>
  </div>
</div>

app/views/vehiculos/update.html.erb
<h1>Vehiculos#update</h1>
<p>Find me in app/views/vehiculos/update.html.erb</p>