config/routes.rb
Rails.application.routes.draw do

  resources :contact

  get 'reportes/reportes'
  get 'reportes/clientes'
  get 'reportes/usuarios'
  get 'reportes/empleados'

  get 'registration_clients/mis_paquetes'

  get 'checkouts/index'
  post :save_checkout, to: 'checkouts#save_checkout'
  get :view_checkout, to: 'checkouts#view_checkout'
  post :confirm_checkout, to: 'checkouts#confirm_checkout'

  devise_for :clients, controllers: { sessions: 'clients/sessions', 
                                      registrations: 'clients/registrations',
                                      confirmations: 'clients/confirmations',
                                      passwords: 'clients/passwords' }

  devise_for :users, controllers: { sessions: 'users/sessions', 
                                    registrations: 'users/registrations',
                                    confirmations: 'users/confirmations',
                                    passwords: 'users/passwords' }

  root to: 'static_pages#home'
  get :admin_home, to: 'admin#home'

  #Paginas estaticas
  get :quienes_somos, to: 'static_pages#who_we_are'
  get :servicios, to: 'static_pages#services'
  get :contacto, to: 'static_pages#contact'

  resources :registrations
  resources :employees
  resources :registration_clients
  resources :packs
  resources :vehiculos
  resources :rutas

  get :select_vehiculo, to: 'rutas#select_vehiculo'
  post :confirm_vehiculo, to: 'rutas#confirm_vehiculo'

  get :select_packs, to: 'rutas#select_packs'
  post :confirm_packs, to: 'rutas#confirm_packs'

  get :select_ruta, to: 'rutas#select_ruta'
  post :confirmar_rutas, to: 'rutas#confirmar_rutas'

  get :index_rutas, to: 'rutas#index_rutas'

  post :client_modal_create, to: 'registration_clients#modal_create'
  get '/json_client/(:id)', to: 'registration_clients#json_client'

  get :nomina, to: 'employees#nomina'
end

app/controllers/registration_clients_controller.rb
# Controller Clients
class RegistrationClientsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_model

  def index
    @clients = Client.all.order(:email)
  end

  def show
  end
  
  def new
  end

  def edit
  end
  
  def create
    client = Client.new client_params
    if client.save
      flash[:notice] = 'Cliente creado'
      redirect_to registration_clients_path
    else
      flash[:alert] = client.errors
      redirect_to new_registration_client_path
    end
  end

  def modal_create
    @client = Client.new client_params
    if @client.save
      render json: @client
    else
      render json: { errors: @client.errors }
    end
  end

  def json_client
    @client = Client.find(params[:id])
    if @client
      render json: @client
    else
      render json: { errors: 'Not found' }
    end
  end

  def update
    if @client.update_attributes client_params
      flash[:notice] = 'Cliente actualizado'
      redirect_to registration_clients_path
    else
      flash[:alert] = @client.errors
      redirect_to edit_registration_client_path
    end
  end
  
  def destroy
    if @client.destroy
      flash[:notice] = 'Cliente eliminado'
      redirect_to registration_clients_path
    else
      flash[:alert] = @client.errors
      redirect_to edit_registration_client_path
    end
  end

  def mis_paquetes
    @packs = Pack.all.where(client_id: current_client.id)
  end

  private
  def find_model
    @client = Client.find(params[:id]) if params[:id]
  end

  def client_params
    params.require(:client).permit(:email, :password, :phone, :residence, :name, :last_name)
  end
end

app/views/registration_clients/_form.html.erb
<%= form_for(form_model, url: form_url, method: form_method) do |f| %>
<div class="row">
  <div class="col-md-6 form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: 'form-control'  %>
  </div>
  <div class="col-md-6 form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control'  %>
  </div>
</div>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: 'form-control'  %>
  </div>
  <div class="row">
    <div class="col-md-12 form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
    </div>
    <!--
    <div class="col-md-6 form-group">
      <%= f.label :confirm_password %>
      <%= f.password_field :confirm_password, class: 'form-control' %>
    </div>
    -->
  </div>
  <div class="row">
    <div class="col-md-6 form-group">
      <%= f.label :phone %>
      <%= f.text_field :phone, class: 'form-control'  %>
    </div>
  </div>
  <div class="form-group">
      <%= f.label :residence %>
      <%= f.text_field :residence, class: 'form-control'  %>
  </div>
  <div>
      <%= f.submit :guardar, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/registration_clients/edit.html.erb
<div id="EditClient" class="animated fadeIn">

  <h1 class="title">Editar Cliente</h1>

  <%= link_to registration_clients_path do %>
    <%= fa_icon "chevron-left" %>
    <span>Regresar</span>
  <%- end %>

  <div class="col-md-8">
	<%= render 'form', form_model: @client, form_url: registration_client_path(@client.id), form_method: :patch %>
  </div>
</div>

app/views/registration_clients/index.html.erb
<div class="animated fadeIn">
  
  <h1 class="title">Listado Clientes</h1>

  <%= link_to admin_home_path do %>
    <%= fa_icon "chevron-left" %>
    <span>Regresar</span>
  <%- end %>
  <%= link_to new_registration_client_path do %>
    <%= fa_icon "user-plus" %>
    <span>Nuevo Cliente</span>
  <%- end %>

  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Apellidos</th>
        <th scope="col">Nombre</th>
        <th scope="col">Email</th>
        <th scope="col">Teléfono</th>
        <th scope="col">Residencia</th>
        <th scope="col">Cliente desde</th>
        <th scope="col">Opciones</th>
      </tr>
    </thead>
    <tbody>
      <% @clients.each do |client| %>
        <tr>
          <th scope="row"><%= client.last_name %></th>
          <td><%= client.name %></td>
          <td><%= client.email %></td>
          <td><%= client.phone %></td>
          <td><%= client.residence %></td>
          <td><%= client.created_at.to_date %></td>
          <td>
              <%= link_to edit_registration_client_path(client.id) do %>
                <%= fa_icon "edit 2x" %>
              <%- end %>
              <%= link_to registration_client_path(client.id), method: :delete, data: { confirm: 'Está seguro que desea borrar este elemento?' } do %>
                <%= fa_icon "trash 2x" %>
              <%- end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/registration_clients/mis_paquetes.html.erb
<div class="animated fadeIn">
    
  <h1 class="title">Listado Paquetes</h1>

  <%= link_to admin_home_path do %>
    <%= fa_icon "chevron-left" %>
    <span>Regresar</span>
  <%- end %>

  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Cliente</th>
        <th scope="col">Destino</th>
        <th scope="col">Dimensiones</th>
        <th scope="col">Peso</th>
        <th scope="col">Estatus</th>
      </tr>
    </thead>
    <tbody>
      <% @packs.each do |pack| %>
        <tr>
          <th scope="row"><%= pack.client_id %></th>
          <td><%= pack.address_state %></td>
          <td><%= "#{pack.size_x}, #{pack.size_y}, #{pack.size_z}"  %></td>
          <td><%= pack.weight %></td>
          <td><%= pack.status %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/registration_clients/new.html.erb
<div id="NewClient" class="animated fadeIn">

  <h1 class="title">Nuevo Cliente</h1>

  <%= link_to registration_clients_path do %>
    <%= fa_icon "chevron-left" %>
    <span>Regresar</span>
  <%- end %>

  <div class="col-md-8">
	<%= render 'form', form_model: :client, form_url: registration_clients_url, form_method: :post %>
  </div>
</div>

app/views/registration_clients/show.html.erb
<div class="card text-white bg-success mt-5">
  <div class="card-header">Mi cuenta</div>
  <div class="card-body">
    <h4 class="card-title">Correo: <%= current_client.email %></h4>
    <p class="card-text"></p>
  </div>
</div>

<%= button_to 'Cambiar contraseña', '', method: :get, class: 'btn btn-success mt-3' %>