config/routes.rb
Rails.application.routes.draw do

  resources :contact

  get 'reportes/reportes'
  get 'reportes/clientes'
  get 'reportes/usuarios'
  get 'reportes/empleados'

  get 'registration_clients/mis_paquetes'

  get 'checkouts/index'
  post :save_checkout, to: 'checkouts#save_checkout'
  get :view_checkout, to: 'checkouts#view_checkout'
  post :confirm_checkout, to: 'checkouts#confirm_checkout'

  devise_for :clients, controllers: { sessions: 'clients/sessions', 
                                      registrations: 'clients/registrations',
                                      confirmations: 'clients/confirmations',
                                      passwords: 'clients/passwords' }

  devise_for :users, controllers: { sessions: 'users/sessions', 
                                    registrations: 'users/registrations',
                                    confirmations: 'users/confirmations',
                                    passwords: 'users/passwords' }

  root to: 'static_pages#home'
  get :admin_home, to: 'admin#home'

  #Paginas estaticas
  get :quienes_somos, to: 'static_pages#who_we_are'
  get :servicios, to: 'static_pages#services'
  get :contacto, to: 'static_pages#contact'

  resources :registrations
  resources :employees
  resources :registration_clients
  resources :packs
  resources :vehiculos
  resources :rutas

  get :select_vehiculo, to: 'rutas#select_vehiculo'
  post :confirm_vehiculo, to: 'rutas#confirm_vehiculo'

  get :select_packs, to: 'rutas#select_packs'
  post :confirm_packs, to: 'rutas#confirm_packs'

  get :select_ruta, to: 'rutas#select_ruta'
  post :confirmar_rutas, to: 'rutas#confirmar_rutas'

  get :index_rutas, to: 'rutas#index_rutas'

  post :client_modal_create, to: 'registration_clients#modal_create'
  get '/json_client/(:id)', to: 'registration_clients#json_client'

  get :nomina, to: 'employees#nomina'
end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController
  def index
    @clients = Client.all
  end

  def save_checkout
    ticket = Pack.get_ticket
    params["pack"].each { |p|
      Pack.create(ticket: ticket + 1,
                  client_id: params["client"],
                  addressee: p[1]["addressee"],
                  address_state: p[1]["address_state"],
                  address_city: p[1]["address_city"],
                  address_pc: p[1]["address_pc"],
                  address_street: p[1]["address_street"],
                  size_x: p[1]["size_x"],
                  size_y: p[1]["size_y"],
                  size_z: p[1]["size_z"],
                  weight: p[1]["weight"],
                  description: p[1]["description"],
                  status: 0)
    }
    redirect_to view_checkout_path
  end

  def view_checkout
    @last_ticket = Pack.last_ticket
  end

  def confirm_checkout
  end
end

app/helpers/checkouts_helper.rb
module CheckoutsHelper
end

app/views/checkouts/_info_client.html.erb
<button type="button" class="btn btn-success" data-toggle="modal" data-target="#cliente" >Seleccionar Cliente</button>

<div class="card text-white bg-primary mt-3">
  <div class="card-header">Cliente</div>
  <div class="card-body">
    <h4 class="card-title">Nombre: </h4>
    <p class="card-text" id="card_nombre_cliente" ></p>
    <h4 class="card-title">Residencia: </h4>
    <p class="card-text" id="card_residencia_cliente" ></p>
    <h4 class="card-title">Folio: </h4>
    <p class="card-text" id="card_folio_cliente" ></p>
  </div>
</div>

app/views/checkouts/_info_pack.html.erb
<button type="button" class="btn btn-success" data-toggle="modal" data-target="#paquete" >Nuevo Paquete</button>

<div class="card text-white bg-primary mt-3"  id="lista_paquetes">
  <div class="card-header">Paquetes registrados</div>
  <div class="card-body">
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">Descripción</th>
          <th scope="col">Dimensiones</th>
          <th scope="col">Peso</th>
          <th scope="col">Destinatario</th>
          <th scope="col">Destino</th>
        </tr>
      </thead>
      <tbody id="table-rows">
        <!-- Aqui se va a estar agregando de una en una -->
      </tbody>
    </table>
  </div>
</div>

app/views/checkouts/_modal_register_client.html.erb
<div class="modal" id="cliente">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Seleccionar cliente</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_for(:client) do |f| %>
          <div class="col-md-12 form-group">
            <%= f.label :correo %>
            <%= f.select(:email, Client.all.pluck(:email, :id), {include_blank: true}, {id: 'select-beast' }) %>
          </div>
        <%- end %>
        <h5 class="card-title">Nombre: </h5>
        <p class="card-text" id="nombre_cliente"></p>
        <h5 class="card-title">Residencia: </h5>
        <p class="card-text" id="residencia_cliente"></p>
        <h5 class="card-title">Telefono: </h5>
        <p class="card-text" id="telefono_cliente"></p>
        <h5 class="card-title">Folio: </h5>
        <p class="card-text" id="folio_cliente"></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" id="button_select">Seleccionar</button>
      </div>
    </div>
  </div>
</div>

<div class="modal" id="form_client">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Seleccionar cliente</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_for(:client, url: client_modal_create_url, method: :post, html: {id: 'new_client_form'}) do |f| %>
        <div class="row">
          <div class="col-md-6 form-group">
            <%= f.label :last_name %>
            <%= f.text_field :last_name, class: 'form-control'  %>
          </div>
          <div class="col-md-6 form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control'  %>
          </div>
        </div>
          <div class="form-group">
            <%= f.label :email %>
            <%= f.text_field :email, class: 'form-control'  %>
          </div>
          <div class="row">
            <div class="col-md-12 form-group">
              <%= f.label :password %>
              <%= f.password_field :password, class: 'form-control' %>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6 form-group">
              <%= f.label :phone %>
              <%= f.text_field :phone, class: 'form-control'  %>
            </div>
          </div>
          <div class="form-group">
              <%= f.label :residence %>
              <%= f.text_field :residence, class: 'form-control'  %>
          </div>
          <div>
              <%= f.submit :guardar, class: 'btn btn-primary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/checkouts/_modal_register_pack.html.erb
<div class="modal" id="paquete">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Registrar paquete</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= simple_form_for(:pack, html: { id: 'new_pack_form' }) do |f| %>
        <div class="modal-body">
          <div class="row">
            <div class="col-md-12 form-group">
              <%= f.label :addressee %>
              <%= f.text_field :addressee, class: 'form-control'  %>
            </div>
            <div class="col-md-12 form-group">
              <%= f.label :address_street %>
              <%= f.text_field :address_street, class: 'form-control'  %>
            </div>
            <div class="col-md-8 form-group">
              <%= f.label :address_city %>
              <%= f.text_field :address_city, class: 'form-control'  %>
            </div>
            <div class="col-md-4 form-group">
              <%= f.label :address_pc %>
              <%= f.text_field :address_pc, class: 'form-control'  %>
            </div>
            <div class="col-md-12 form-group">
              <%= f.label :address_state %>
              <%= f.text_field :address_state, class: 'form-control' %>
            </div>
            <div class="col-md-12 form-group">
              <%= f.label :description %>
              <%= f.text_field :description, class: 'form-control' %>
            </div>
            <div class="col-md-3 form-group">
              <%= f.label :size_x %>
              <%= f.number_field :size_x, class: 'form-control' %>
            </div>
            <div class="col-md-3 form-group">
              <%= f.label :size_y %>
              <%= f.number_field :size_y, class: 'form-control' %>
            </div>
            <div class="col-md-3 form-group">
              <%= f.label :size_z %>
              <%= f.number_field :size_z, class: 'form-control' %>
            </div>
            <div class="col-md-3 form-group">
              <%= f.label :weight %>
              <%= f.number_field :weight, class: 'form-control' %>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary disabled" id="guardar_paquete">Guardar</button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/checkouts/index.html.erb
<div class="animated fadeIn">
  <div class="row">
    <div class="col-md-12">
      <div class="card text-white bg-primary mb-3" style="">
        <div class="card-header">
          <h1>Recepción</h1>
        </div>
        <div class="card-body">
          <div class="row">
            <div class="col-md-4">
              <div class="d-flex justify-content-center">
                <div class="col-md-12">
                  <%= render 'info_client' %>
                </div>
              </div>
            </div>
            <div class="col-md-8">
              <div class="d-flex justify-content-center">
                <div class="col-md-12">
                  <%= render 'info_pack' %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <button type="button" class="btn btn-success float-right" id="save_checkout" action="<%= save_checkout_path %>" >Guardar</button>
    </div>
  </div>
</div>

<%= render 'modal_register_client' %>
<%= render 'modal_register_pack' %>

app/views/checkouts/view_checkout.html.erb
<div class="animated fadeIn">
  <div class="row">
    <div class="col-md-12">
      <div class="card text-white bg-primary mb-3" style="">
        <div class="card-header">
          <h1>Confirmación de Pago</h1>
        </div>
        <div class="card-body">
          <table class="table table-hover">
            <thead>
              <tr>
                <th scope="col">Descripción</th>
                <th scope="col">Dimensiones</th>
                <th scope="col">Peso</th>
                <th scope="col">Destinatario</th>
                <th scope="col">Destino</th>
                <th scope="col">Precio</th>
              </tr>
            </thead>
            <tbody id="table-rows">
              <!-- Aqui se va a estar agregando de una en una -->
              <% @last_ticket.each do |pack| %>
                <tr>
                  <td><%= pack.description %></td>
                  <td><%= "[#{pack.size_x} cm, #{pack.size_y} cm, #{pack.size_z} cm]" %></td>
                  <td><%= pack.weight %></td>
                  <td><%= pack.addressee %></td>
                  <td><%= "#{pack.address_street}, #{pack.address_city}, #{pack.address_pc}, #{pack.address_state}"  %></td>
                  <td><%= pack.weight * 345.2 %></td>
                </tr>
              <%- end %>
            </tbody>
            <tfoot>
              <tr>
                <th scope="col"></th>
                <th scope="col"></th>
                <th scope="col"></th>
                <th scope="col"></th>
                <th scope="col"></th>
                <th scope="col">Precio</th>
              </tr>
            </tfoot>
          </table>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <%= button_to 'Finalizar', admin_home_path, class: 'btn btn-success float-right', method: :get %>
        </div>
      </div>
    </div>
  </div>
</div>